### ISSUE TITLE
Criação do banco de dados inicial (PostgreSQL) com base na modelagem realizada

### ISSUE THREAD

**Issue by Reeaper** [Echo-Emotional-Group/EchoEmotionalServer#3]
Criação do banco de dados com base em nossa modelagem inicial

![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/122502559/28fa44a2-9610-4ed3-9a4c-b239a2302597)

**Comment by FelipeAlvesTs** [comment]
E ai @Reeaper tudo certo precisa de ajuda ?

**Comment by Reeaper** [comment]
por enqt ta dboa,assim q eu terminar cada uma das tabelas eu mando no grupo

**Comment by Reeaper** [comment]
Diagrama da base de dados
Tabela Perfil_user: responsável por criar a conta do usuário utilizando a conta do Facebook

Tabela emotion: responsável por capturar o id do post do Facebook e adicionar uma  
descrição sobre como a pessoa estava se sentindo quando publicou o post

Tabela reaction:contem a lista de reações que serão utilizadas para reagir ao post(lista responsável pelos emogis de reação)

Tabela emotion_reaction: responsável por unir dados de ambas as tabelas permitindo maior flexibilidade ao escolher reações, permitindo sendo mais de uma reação por post e com descrição opcional


![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/0581d76d-fb62-4ac2-8152-cc5a6bf9d4c5)



![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/e2c036ce-a3fc-49ed-aa29-3005ae6ef504)



![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/41898b40-6b0b-49fe-a7a6-0ccd9195048c)



![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/e20321f1-b0ae-4e70-a566-089f37ced43d)

**Comment by Reeaper** [comment]
--criando tabela de emoçao
CREATE TABLE emotion (
    id SERIAL PRIMARY KEY,
    id_reactions INT REFERENCES reaction(id) ON DELETE cascade,
    id_post VARCHAR NOT null references perfil_user(id_accont_facebook),
    emotion_desc TEXT NOT NULL
);

--removendo coluna id_reactions
alter table emotion
drop column id_reactions;

-- Inserir uma descrição de emoção associada a reações e a um post teste
INSERT INTO emotion (id_post, emotion_desc) 
VALUES ('123456789', 'comi pipoca com sal');


--inserindo outros valores
INSERT INTO emotion (id_post, emotion_desc) 
VALUES ('123274768', 'tomei um tacácá'),
	 ('353688986','ganhei na loteria'),
	 ('626179765','cai de elo no lol'),
	 ('456735890','minha fonte do pc queimou');


select * from emotion;

**Comment by Reeaper** [comment]
--criando lista de emoçoes

CREATE TYPE reactions AS enum
(
	'calmo',
    'animado',
    'agitado',
    'cansado',
    'culpado',
    'desanimado', 
    'feliz', 
    'irritado',
    'triste'
);

--criando tabela de reaçao

CREATE TABLE reaction (
    id SERIAL PRIMARY KEY,
    tipo reactions
);

--teste de inserção de valores

INSERT INTO reaction 
(tipo) VALUES ('calmo');


--inserindo valores

INSERT INTO reaction 
(tipo) VALUES ('animado'),
	('agitado'),
	('cansado'),
	('culpado'),
	('desanimado'),
	('feliz'),
	('irritado'),
	('triste');


--exibindo resultado

select * from reaction;

**Comment by Reeaper** [comment]
-- Criar tabela de junção para associar emoções, reações e posts
CREATE TABLE emotion_reaction (
    emotion_id INT,
    reaction_id INT,
    id_accont_facebook TEXT NOT NULL,
    FOREIGN KEY (emotion_id) REFERENCES emotion(id) ON DELETE CASCADE,
    FOREIGN KEY (reaction_id) REFERENCES reaction(id) ON DELETE CASCADE,
    FOREIGN KEY (id_accont_facebook) REFERENCES perfil_user(id_accont_facebook) ON DELETE CASCADE,
    PRIMARY KEY (emotion_id, reaction_id, id_accont_facebook)
);


--testando inserçao de dois valores para o mesmo post/emotion_desc
INSERT INTO emotion_reaction (emotion_id, reaction_id, id_accont_facebook) 
VALUES 
(6, 1, '123456789'),
(6, 2, '123456789');


--inserindo valores restantes
INSERT INTO emotion_reaction (emotion_id, reaction_id, id_accont_facebook) 
VALUES (7,3,'123274768'),
	   (7,4,'123274768'),
	   
	   (8,5,'353688986'),
	   (8,6,'353688986'),

	   (9,7,'626179765'),
	   (9,2,'626179765'),
	   
	   (10,1,'456735890'),
	   (10,7,'456735890');
--exibindo resultado
select * from emotion_reaction;

**Comment by Reeaper** [comment]
--criando a tabela de perfil do usuario
CREATE TABLE perfil_user (
    id_accont_facebook TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
     data_post DATE NOT null,
    data_nasc DATE NOT NULL,
    data_registro DATE DEFAULT CURRENT_TIMESTAMP
);

--inserindo valores (id da conta,nome completo,data do post e data de nascimento)
INSERT INTO perfil_user (id_accont_facebook,full_name,data_post, data_nasc, data_registro)
VALUES
    ('123456789','Felipe Alves','2012-10-20', '2003-05-03', '2024-05-03'),
    ('123274768','Thatylla tata', '2020-06-30','1989-11-22', '2021-01-15'),
    ('353688986','Jesus Sena','2017-05-21', '1789-12-25', '2012-06-13'),
    ('626179765','Victor Uemura','2023-08-14','2015-07-07', '2027-06-18'),
    ('456735890','Akira Yuki','2024-03-06','2005-03-02', '2009-08-30');
   
   select * from perfil_user;

**Comment by Reeaper** [comment]
Tabelas preenchidas com exemplos:


Tabela perfil_user:
![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/cf98bf8d-eebd-4254-9eec-94e279d43227)

Tabela emotion:
![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/f83ce1b9-a721-413d-83ee-6444c84411ee)

Tabela reaction:
![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/09ad6586-0c3f-4b8e-9311-9cf6d92a214a)

Tabela emotion_reaction:
![Image](https://github.com/Echo-Emotional-Group/EchoEmotionalServer/assets/77421272/fafda6bf-49f6-4f9a-b95a-7d5e2f8d1a0c)
